### ISSUE TITLE
 fdsnxml2inv - import_inv dlsv : rejected units

### ISSUE THREAD

**Issue by lemarchandarnaud** [SeisComP3/seiscomp3#113] opened 2017-03-31 09:52 UTC
Dear Jan
Currently only "M/S", "M/S^2", "M", "C" and "PA" are supported as input units in by the import tools. This is a real problem whe you want to deal with others kind of geophysical data.
regards
arnaud

**Comment by gempa-jabe** [comment] 2017-04-03 07:23
This is a duplicate of #111. With *supported* you refer to the creation of Streams and not AuxStreams, right?

**Comment by lemarchandarnaud** [comment] 2017-04-03 08:01
The dlsv-conversion-fix also sorts ou this issue but it is not exactly the same as  the issue 111 even if they likely linked.

**Closed** 2017-04-03 08:03 UTC
Labels: implemented
